### ISSUE TITLE
<a id="menu-ViewModelExplorer" href="#sidr">ViewModel Explorer</a> shown on the left top of my browser window

### ISSUE THREAD

**Issue by kevingzhang** [ManuelDeLeon/viewmodel-explorer#2]
Click this <a> will open a side menu. I do not want to show this <a> in my window, how can I hide or remove it?

thank you

**Comment by ManuelDeLeon** [comment]
It's debug only. I'm in the process of updating the documentation to make it clear.

I don't think the (debug only) link is obtrusive but if enough people complain I'll make the ViewModel package stop loading the side panel automatically.

**Comment by kevingzhang** [comment]
Not big issue, just make sure it can be removed. I noticed it won't shown on production but that area has special usage in my app, that's why I was asking.

**Comment by ManuelDeLeon** [comment]
ViewModel stopped loading the side panel automatically. I need to think about this.
